### ISSUE TITLE
Build Login component

### ISSUE THREAD

**Issue by cammac60** [hfaerber/Palette_Picker#19]
Users would like a place to login to the application and to be told if their login was unsuccessful (and why). As a FE developer I should allow them to login and provide a clear and concise error message if their login fails.

- [x] Setup stateful component with a name, password, and error message in state.
- [x] Setup form validation.
- [ ] Setup api call to log the user in.
- [x] Setup redirection to the homepage.
- [x] Style component.
- [ ] Test component.

![Palette-Picker](https://user-images.githubusercontent.com/47998896/73714563-6cc0bf80-46ce-11ea-976f-0e9c984f7945.png)

**Comment by cammac60** [comment]
Although not explicitly laid out in the specs we could add some login functionality by: 
1. Creating a `users` database to hold users. 
2. Adding a user_id column to the projects table.
3. On login - Make a post to the users endpoint and check to see if the user exists. If they don't create a new user, if they do validate their login and return the appropriate response. 

If we wish to hold off on this for now to focus on the spec requirements we can move the state hook functionality to the App component and just pass down relevant info as props. This does mean that all users will share the same data and the login component would be just for show.

**Comment by hfaerber** [comment]
I'm going to try to get the login test working if I can.
